import { type Book } from './books.model';

export const BOOKS: Book[] = [
  {
    id: '1',
    name: 'The Midnight Library',
    image: 'https://picsum.photos/200/300',
    genre: ['Fiction', 'Fantasy'],
    author: 'Matt Haig',
    publishDate: '2020-08-13',
    price: 1499,
  },
  {
    id: '2',
    name: 'Dune',
    image: 'https://picsum.photos/200/300',
    genre: ['Science Fiction', 'Adventure'],
    author: 'Frank Herbert',
    publishDate: '1965-08-01',
    price: 999,
  },
  {
    id: '3',
    name: 'To Kill a Mockingbird',
    image: 'https://picsum.photos/200/300',
    genre: ['Fiction', 'Classic'],
    author: 'Harper Lee',
    publishDate: '1960-07-11',
    price: 799,
  },
  {
    id: '4',
    name: '1984',
    image: 'https://picsum.photos/200/300',
    genre: ['Dystopian', 'Science Fiction'],
    author: 'George Orwell',
    publishDate: '1949-06-08',
    price: 899,
  },
  {
    id: '5',
    name: 'The Great Gatsby',
    image: 'https://picsum.photos/200/300',
    genre: ['Fiction', 'Classic'],
    author: 'F. Scott Fitzgerald',
    publishDate: '1925-04-10',
    price: 699,
  },
  {
    id: '6',
    name: "Harry Potter and the Philosopher's Stone",
    image: 'https://picsum.photos/200/300',
    genre: ['Fantasy', 'Young Adult'],
    author: 'J.K. Rowling',
    publishDate: '1997-06-26',
    price: 1099,
  },
  {
    id: '7',
    name: 'The Catcher in the Rye',
    image: 'https://picsum.photos/200/300',
    genre: ['Fiction', 'Coming-of-age'],
    author: 'J.D. Salinger',
    publishDate: '1951-07-16',
    price: 849,
  },
  {
    id: '8',
    name: 'Pride and Prejudice',
    image: 'https://picsum.photos/200/300',
    genre: ['Romance', 'Classic'],
    author: 'Jane Austen',
    publishDate: '1813-01-28',
    price: 599,
  },
  {
    id: '9',
    name: 'The Hobbit',
    image: 'https://picsum.photos/200/300',
    genre: ['Fantasy', 'Adventure'],
    author: 'J.R.R. Tolkien',
    publishDate: '1937-09-21',
    price: 949,
  },
  {
    id: '10',
    name: 'The Da Vinci Code',
    image: 'https://picsum.photos/200/300',
    genre: ['Thriller', 'Mystery'],
    author: 'Dan Brown',
    publishDate: '2003-03-18',
    price: 1299,
  },
  {
    id: '11',
    name: 'The Alchemist',
    image: 'https://picsum.photos/200/300',
    genre: ['Fiction', 'Philosophy'],
    author: 'Paulo Coelho',
    publishDate: '1988-01-01',
    price: 1099,
  },
  {
    id: '12',
    name: 'Brave New World',
    image: 'https://picsum.photos/200/300',
    genre: ['Science Fiction', 'Dystopian'],
    author: 'Aldous Huxley',
    publishDate: '1932-01-01',
    price: 899,
  },
  {
    id: '13',
    name: 'The Hunger Games',
    image: 'https://picsum.photos/200/300',
    genre: ['Young Adult', 'Science Fiction'],
    author: 'Suzanne Collins',
    publishDate: '2008-09-14',
    price: 1199,
  },
  {
    id: '14',
    name: 'The Shining',
    image: 'https://picsum.photos/200/300',
    genre: ['Horror', 'Thriller'],
    author: 'Stephen King',
    publishDate: '1977-01-28',
    price: 1299,
  },
  {
    id: '15',
    name: 'The Girl with the Dragon Tattoo',
    image: 'https://picsum.photos/200/300',
    genre: ['Crime', 'Mystery'],
    author: 'Stieg Larsson',
    publishDate: '2005-08-01',
    price: 1399,
  },
  {
    id: '16',
    name: "The Hitchhiker's Guide to the Galaxy",
    image: 'https://picsum.photos/200/300',
    genre: ['Science Fiction', 'Comedy'],
    author: 'Douglas Adams',
    publishDate: '1979-10-12',
    price: 999,
  },
  {
    id: '17',
    name: 'The Kite Runner',
    image: 'https://picsum.photos/200/300',
    genre: ['Fiction', 'Historical'],
    author: 'Khaled Hosseini',
    publishDate: '2003-05-29',
    price: 1199,
  },
  {
    id: '18',
    name: 'The Martian',
    image: 'https://picsum.photos/200/300',
    genre: ['Science Fiction', 'Adventure'],
    author: 'Andy Weir',
    publishDate: '2011-09-27',
    price: 1299,
  },
  {
    id: '19',
    name: "The Handmaid's Tale",
    image: 'https://picsum.photos/200/300',
    genre: ['Dystopian', 'Speculative Fiction'],
    author: 'Margaret Atwood',
    publishDate: '1985-06-14',
    price: 1099,
  },
  {
    id: '20',
    name: 'The Fault in Our Stars',
    image: 'https://picsum.photos/200/300',
    genre: ['Young Adult', 'Romance'],
    author: 'John Green',
    publishDate: '2012-01-10',
    price: 999,
  },
  {
    id: '21',
    name: 'Sapiens: A Brief History of Humankind',
    image: 'https://picsum.photos/200/300',
    genre: ['Non-fiction', 'History'],
    author: 'Yuval Noah Harari',
    publishDate: '2011-01-01',
    price: 1599,
  },
  {
    id: '22',
    name: 'The Lord of the Rings',
    image: 'https://picsum.photos/200/300',
    genre: ['Fantasy', 'Epic'],
    author: 'J.R.R. Tolkien',
    publishDate: '1954-07-29',
    price: 1799,
  },
  {
    id: '23',
    name: 'Becoming',
    image: 'https://picsum.photos/200/300',
    genre: ['Non-fiction', 'Autobiography'],
    author: 'Michelle Obama',
    publishDate: '2018-11-13',
    price: 1499,
  },
  {
    id: '24',
    name: 'One Hundred Years of Solitude',
    image: 'https://picsum.photos/200/300',
    genre: ['Magical Realism', 'Literary Fiction'],
    author: 'Gabriel García Márquez',
    publishDate: '1967-05-30',
    price: 1099,
  },
  {
    id: '25',
    name: 'The Silent Patient',
    image: 'https://picsum.photos/200/300',
    genre: ['Thriller', 'Mystery'],
    author: 'Alex Michaelides',
    publishDate: '2019-02-05',
    price: 1399,
  },
  {
    id: '26',
    name: 'The Catcher in the Rye',
    image: 'https://picsum.photos/200/300',
    genre: ['Fiction', 'Coming-of-age'],
    author: 'J.D. Salinger',
    publishDate: '1951-07-16',
    price: 999,
  },
  {
    id: '27',
    name: 'Educated',
    image: 'https://picsum.photos/200/300',
    genre: ['Non-fiction', 'Memoir'],
    author: 'Tara Westover',
    publishDate: '2018-02-20',
    price: 1299,
  },
  {
    id: '28',
    name: 'The Pillars of the Earth',
    image: 'https://picsum.photos/200/300',
    genre: ['Historical Fiction', 'Epic'],
    author: 'Ken Follett',
    publishDate: '1989-10-01',
    price: 1599,
  },
  {
    id: '29',
    name: 'The Immortal Life of Henrietta Lacks',
    image: 'https://picsum.photos/200/300',
    genre: ['Non-fiction', 'Science'],
    author: 'Rebecca Skloot',
    publishDate: '2010-02-02',
    price: 1199,
  },
  {
    id: '30',
    name: 'The name of the Wind',
    image: 'https://picsum.photos/200/300',
    genre: ['Fantasy', 'Adventure'],
    author: 'Patrick Rothfuss',
    publishDate: '2007-03-27',
    price: 1499,
  },
];
